import type {
    ReportColumn,
    ReportPreset,
    ReportPresetKey,
} from '@/types/reports';

const NOTES_VIEW_COLUMNS: ReportColumn[] = [
    { field: 'department', headerKey: 'reports.columns.department' },
    { field: 'rank_category', headerKey: 'reports.columns.rankCategory' },
    { field: 'rank', headerKey: 'reports.columns.rank' },
    { field: 'military_number', headerKey: 'reports.columns.militaryNumber' },
    { field: 'gender', headerKey: 'reports.columns.gender' },
    { field: 'fullname_ar', headerKey: 'reports.columns.fullname' },
    { field: 'mvdate', headerKey: 'reports.columns.date' },
    {
        field: 'dakhool',
        headerKey: 'reports.columns.checkIn',
        issueField: 'hasEntryIssue',
    },
    {
        field: 'khorooj',
        headerKey: 'reports.columns.checkOut',
        issueField: 'hasExitIssue',
    },
    { field: 'notes', headerKey: 'reports.columns.notes' },
    { field: 'created_by', headerKey: 'reports.columns.createdBy' },
];

const INDIVIDUAL_COLUMNS: ReportColumn[] = [
    { field: 'department', headerKey: 'reports.columns.department' },
    { field: 'rank_category', headerKey: 'reports.columns.rankCategory' },
    { field: 'rank', headerKey: 'reports.columns.rank' },
    { field: 'military_number', headerKey: 'reports.columns.militaryNumber' },
    { field: 'fullname_ar', headerKey: 'reports.columns.fullname' },
    { field: 'gender', headerKey: 'reports.columns.gender' },
    { field: 'mvdate', headerKey: 'reports.columns.date' },
    { field: 'mvtime', headerKey: 'reports.columns.time' },
    { field: 'mvtype', headerKey: 'reports.columns.type' },
    { field: 'gate', headerKey: 'reports.columns.gate' },
    { field: 'base', headerKey: 'reports.columns.base' },
];

const COMPANIES_BASIC_COLUMNS: ReportColumn[] = [
    { field: 'department', headerKey: 'reports.columns.company' },
    { field: 'fullname_en', headerKey: 'reports.columns.fullname' },
    { field: 'nationality', headerKey: 'reports.columns.nationality' },
    { field: 'phone_number', headerKey: 'reports.columns.phone' },
    { field: 'checkin', headerKey: 'reports.columns.checkIn' },
    { field: 'checkout', headerKey: 'reports.columns.checkOut' },
];

const COMPANIES_ISSUES_COLUMNS: ReportColumn[] = [
    { field: 'department', headerKey: 'reports.columns.company' },
    { field: 'fullname_en', headerKey: 'reports.columns.fullname' },
    { field: 'nationality', headerKey: 'reports.columns.nationality' },
    { field: 'phone', headerKey: 'reports.columns.phone' },
    { field: 'checkin', headerKey: 'reports.columns.checkIn' },
    { field: 'checkout', headerKey: 'reports.columns.checkOut' },
];

const EMPLOYEE_STATUS_COLUMNS: ReportColumn[] = [
    { field: 'department', headerKey: 'reports.columns.department' },
    { field: 'rank', headerKey: 'reports.columns.rank' },
    { field: 'military_number', headerKey: 'reports.columns.militaryNumber' },
    { field: 'fullname', headerKey: 'reports.columns.fullname' },
    { field: 'gender', headerKey: 'reports.columns.gender' },
    { field: 'base', headerKey: 'reports.columns.base' },
];

const EXPIRED_CARDS_COLUMNS: ReportColumn[] = [
    ...EMPLOYEE_STATUS_COLUMNS,
    { field: 'expiry_date', headerKey: 'reports.columns.badgeExpiry' },
    { field: 'active', headerKey: 'reports.columns.activeStatus' },
];

const UNRETURNED_CARDS_COLUMNS: ReportColumn[] = [
    ...EMPLOYEE_STATUS_COLUMNS,
    { field: 'unreturned_card_count', headerKey: 'reports.columns.unreturnedCardCount' },
    { field: 'last_unreturned_card_date', headerKey: 'reports.columns.lastUnreturnedCardDate' },
];

export const reportPresets: Record<ReportPresetKey, ReportPreset> = {
    reports: {
        key: 'reports',
        dateMode: 'single',
        titleKey: 'reports.pages.reports.title',
        descriptionKey: 'reports.pages.reports.description',
        csvFileName: 'Daily-Basic-Report.csv',
        columns: NOTES_VIEW_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        routeKey: 'reports',
    },
    issues: {
        key: 'issues',
        dateMode: 'single',
        titleKey: 'reports.pages.issues.title',
        descriptionKey: 'reports.pages.issues.description',
        csvFileName: 'Daily-Issues-Report.csv',
        columns: NOTES_VIEW_COLUMNS,
        issueHighlight: true,
        allowDeleteNote: false,
        isCompanyVariant: false,
        routeKey: 'issues',
    },
    justified: {
        key: 'justified',
        dateMode: 'range',
        titleKey: 'reports.pages.justified.title',
        descriptionKey: 'reports.pages.justified.description',
        csvFileName: 'Justified-Report.csv',
        columns: NOTES_VIEW_COLUMNS,
        issueHighlight: true,
        allowDeleteNote: true,
        isCompanyVariant: false,
        routeKey: 'justified',
    },
    unjustified: {
        key: 'unjustified',
        dateMode: 'range',
        titleKey: 'reports.pages.unjustified.title',
        descriptionKey: 'reports.pages.unjustified.description',
        csvFileName: 'Unjustified-Report.csv',
        columns: NOTES_VIEW_COLUMNS,
        issueHighlight: true,
        allowDeleteNote: false,
        isCompanyVariant: false,
        routeKey: 'unjustified',
    },
    export: {
        key: 'export',
        dateMode: 'range',
        titleKey: 'reports.pages.export.title',
        descriptionKey: 'reports.pages.export.description',
        csvFileName: 'Export-Issues-Report.csv',
        columns: NOTES_VIEW_COLUMNS,
        issueHighlight: true,
        allowDeleteNote: false,
        isCompanyVariant: false,
        routeKey: 'export_reports',
        groupByDepartmentAndEmployee: true,
        serverCsvExport: true,
    },
    individual: {
        key: 'individual',
        dateMode: 'range',
        titleKey: 'reports.pages.individual.title',
        descriptionKey: 'reports.pages.individual.description',
        csvFileName: 'Individual-Report.csv',
        columns: INDIVIDUAL_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        routeKey: 'individual_report',
    },
    companiesReporting: {
        key: 'companiesReporting',
        dateMode: 'single',
        titleKey: 'reports.pages.companiesReporting.title',
        descriptionKey: 'reports.pages.companiesReporting.description',
        csvFileName: 'Companies-Report.csv',
        columns: COMPANIES_BASIC_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: true,
        routeKey: 'companies_reporting',
    },
    companiesIssues: {
        key: 'companiesIssues',
        dateMode: 'single',
        titleKey: 'reports.pages.companiesIssues.title',
        descriptionKey: 'reports.pages.companiesIssues.description',
        csvFileName: 'Companies-Issues-Report.csv',
        columns: COMPANIES_ISSUES_COLUMNS,
        issueHighlight: true,
        allowDeleteNote: false,
        isCompanyVariant: true,
        routeKey: 'companies_issues',
    },
    deactivatedEmployees: {
        key: 'deactivatedEmployees',
        dateMode: 'none',
        titleKey: 'reports.pages.deactivatedEmployees.title',
        descriptionKey: 'reports.pages.deactivatedEmployees.description',
        csvFileName: 'Deactivated-Employees-Report.csv',
        columns: EMPLOYEE_STATUS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'deactivated_employees',
    },
    expiredCards: {
        key: 'expiredCards',
        dateMode: 'none',
        titleKey: 'reports.pages.expiredCards.title',
        descriptionKey: 'reports.pages.expiredCards.description',
        csvFileName: 'Expired-Cards-Report.csv',
        columns: EXPIRED_CARDS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'expired_cards',
    },
    deactivatedUnreturnedCards: {
        key: 'deactivatedUnreturnedCards',
        dateMode: 'none',
        titleKey: 'reports.pages.deactivatedUnreturnedCards.title',
        descriptionKey: 'reports.pages.deactivatedUnreturnedCards.description',
        csvFileName: 'Deactivated-Unreturned-Cards-Report.csv',
        columns: UNRETURNED_CARDS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'deactivated_unreturned_cards',
    },
    companiesDeactivatedEmployees: {
        key: 'companiesDeactivatedEmployees',
        dateMode: 'none',
        titleKey: 'reports.pages.companiesDeactivatedEmployees.title',
        descriptionKey: 'reports.pages.companiesDeactivatedEmployees.description',
        csvFileName: 'Companies-Deactivated-Employees-Report.csv',
        columns: EMPLOYEE_STATUS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'companies_deactivated_employees',
    },
    companiesExpiredCards: {
        key: 'companiesExpiredCards',
        dateMode: 'none',
        titleKey: 'reports.pages.companiesExpiredCards.title',
        descriptionKey: 'reports.pages.companiesExpiredCards.description',
        csvFileName: 'Companies-Expired-Cards-Report.csv',
        columns: EXPIRED_CARDS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'companies_expired_cards',
    },
    companiesDeactivatedUnreturnedCards: {
        key: 'companiesDeactivatedUnreturnedCards',
        dateMode: 'none',
        titleKey: 'reports.pages.companiesDeactivatedUnreturnedCards.title',
        descriptionKey: 'reports.pages.companiesDeactivatedUnreturnedCards.description',
        csvFileName: 'Companies-Deactivated-Unreturned-Cards-Report.csv',
        columns: UNRETURNED_CARDS_COLUMNS,
        issueHighlight: false,
        allowDeleteNote: false,
        isCompanyVariant: false,
        showMovementFilters: false,
        routeKey: 'companies_deactivated_unreturned_cards',
    },
};
