<?php

use App\Http\Controllers\Inertia\ActivityLogController;
use App\Http\Controllers\Inertia\BadgeDesignController;
use App\Http\Controllers\Inertia\BaseController;
use App\Http\Controllers\Inertia\CheckTimeController;
use App\Http\Controllers\Inertia\CompanyController;
use App\Http\Controllers\Inertia\DepartmentController;
use App\Http\Controllers\Inertia\EmployeeController;
use App\Http\Controllers\Inertia\GateController;
use App\Http\Controllers\Inertia\PlateMovementController;
use App\Http\Controllers\Inertia\ProfileController;
use App\Http\Controllers\Inertia\ReportController;
use App\Http\Controllers\Inertia\RoleAccessController;
use App\Http\Controllers\Inertia\UserController;
use Illuminate\Support\Facades\Route;

// Placeholder pages ported page-by-page from the legacy app — empty for now,
// just enough for the sidebar nav to resolve instead of 404ing.
Route::middleware('auth')->group(function () {
    Route::get('/departments', [DepartmentController::class, 'index'])->name('departments');
    Route::post('/departments', [DepartmentController::class, 'store'])->name('departments.store');
    Route::put('/departments/{department}', [DepartmentController::class, 'update'])->name('departments.update');
    Route::delete('/departments/{department}', [DepartmentController::class, 'destroy'])->name('departments.destroy');
    Route::get('/users', [UserController::class, 'index'])->name('users');
    Route::post('/users', [UserController::class, 'store'])->name('users.store');
    Route::put('/users/{user}', [UserController::class, 'update'])->name('users.update');
    Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('/bases', [BaseController::class, 'index'])->name('bases');
    Route::post('/bases', [BaseController::class, 'store'])->name('bases.store');
    Route::put('/bases/{base}', [BaseController::class, 'update'])->name('bases.update');
    Route::delete('/bases/{base}', [BaseController::class, 'destroy'])->name('bases.destroy');
    Route::post('/bases/{base}/gates', [BaseController::class, 'storeGate'])->name('bases.gates.store');
    Route::put('/gates/{gate}', [BaseController::class, 'updateGate'])->name('gates.update');
    Route::delete('/gates/{gate}', [BaseController::class, 'destroyGate'])->name('gates.destroy');
    Route::post('/bases/{base}/zones', [BaseController::class, 'storeZone'])->name('bases.zones.store');
    Route::put('/zones/{zone}', [BaseController::class, 'updateZone'])->name('zones.update');
    Route::delete('/zones/{zone}', [BaseController::class, 'destroyZone'])->name('zones.destroy');
    Route::get('/employees', [EmployeeController::class, 'index'])->name('employees');
    Route::post('/employees', [EmployeeController::class, 'store'])->name('employees.store');
    Route::put('/employees/{employee}', [EmployeeController::class, 'update'])->name('employees.update');
    Route::delete('/employees', [EmployeeController::class, 'destroy'])->name('employees.destroy');
    Route::post('/employees/approve', [EmployeeController::class, 'approve'])->name('employees.approve');
    Route::post('/employees/set-active', [EmployeeController::class, 'setActive'])->name('employees.set-active');
    Route::get('/employees/access-cards', [EmployeeController::class, 'accessCards'])->name('employees.access-cards');
    Route::post('/employees/print-access-cards', [EmployeeController::class, 'bulkPrintAccessCards'])->name('employees.print-access-cards');
    Route::get('/employees/{employee}/movements', [EmployeeController::class, 'movements'])->name('employees.movements');
    Route::get('/employees/{employee}/access-card', [EmployeeController::class, 'accessCard'])->name('employees.access-card');
    Route::post('/employees/{employee}/print', [EmployeeController::class, 'markPrinted'])->name('employees.print');
    Route::post('/employees/{employee}/badge-log/{badgeLog}/return', [EmployeeController::class, 'returnCard'])->name('employees.badge-log.return');
    Route::post('/employees/{employee}/cars', [EmployeeController::class, 'storeCar'])->name('employees.cars.store');
    Route::patch('/employees/{employee}/cars/{car}', [EmployeeController::class, 'updateCar'])->name('employees.cars.update');
    Route::delete('/employees/{employee}/cars/{car}', [EmployeeController::class, 'destroyCar'])->name('employees.cars.destroy');
    Route::get('/companies', [CompanyController::class, 'index'])->name('companies');
    Route::post('/companies', [CompanyController::class, 'store'])->name('companies.store');
    Route::put('/companies/{company}', [CompanyController::class, 'update'])->name('companies.update');
    Route::delete('/companies/{company}', [CompanyController::class, 'destroy'])->name('companies.destroy');
    Route::get('/companies/{company}', [CompanyController::class, 'show'])->name('companies.show');
    Route::get('/reports', [ReportController::class, 'reports'])->name('reports');
    Route::get('/issues', [ReportController::class, 'issues'])->name('issues');
    Route::get('/justified', [ReportController::class, 'justified'])->name('justified');
    Route::get('/unjustified', [ReportController::class, 'unjustified'])->name('unjustified');
    Route::get('/exportReports', [ReportController::class, 'exportReports'])->name('export_reports');
    Route::get('/IndividualReport', [ReportController::class, 'individualReport'])->name('individual_report');
    Route::get('/companies-reporting', [ReportController::class, 'companiesReporting'])->name('companies_reporting');
    Route::get('/companies-issues', [ReportController::class, 'companiesIssues'])->name('companies_issues');
    Route::get('/reports/deactivated-employees', [ReportController::class, 'deactivatedEmployees'])->name('deactivated_employees');
    Route::get('/reports/expired-cards', [ReportController::class, 'expiredCards'])->name('expired_cards');
    Route::get('/reports/deactivated-unreturned-cards', [ReportController::class, 'deactivatedUnreturnedCards'])->name('deactivated_unreturned_cards');
    Route::get('/reports/companies-deactivated-employees', [ReportController::class, 'companiesDeactivatedEmployees'])->name('companies_deactivated_employees');
    Route::get('/reports/companies-expired-cards', [ReportController::class, 'companiesExpiredCards'])->name('companies_expired_cards');
    Route::get('/reports/companies-deactivated-unreturned-cards', [ReportController::class, 'companiesDeactivatedUnreturnedCards'])->name('companies_deactivated_unreturned_cards');
    Route::get('/reports/data', [ReportController::class, 'data'])->name('reports.data');
    Route::get('/reports/export-csv', [ReportController::class, 'exportCsv'])->name('reports.export-csv');
    Route::get('/reports/companies-data', [ReportController::class, 'companiesData'])->name('reports.companies-data');
    Route::post('/reports/notes', [ReportController::class, 'addNote'])->name('reports.notes.store');
    Route::delete('/reports/notes', [ReportController::class, 'deleteNote'])->name('reports.notes.destroy');
    Route::get('/settings', [CheckTimeController::class, 'index'])->name('settings');
    Route::post('/settings', [CheckTimeController::class, 'store'])->name('settings.store');
    Route::put('/settings/{checkTime}', [CheckTimeController::class, 'update'])->name('settings.update');
    Route::delete('/settings/{checkTime}', [CheckTimeController::class, 'destroy'])->name('settings.destroy');
    Route::get('/badge', [BadgeDesignController::class, 'index'])->name('badge');
    Route::get('/company-badge', [BadgeDesignController::class, 'companyIndex'])->name('company_badge');
    Route::get('/badge/{department}', [BadgeDesignController::class, 'show'])->name('badge.show');
    Route::post('/badge/{department}/front', [BadgeDesignController::class, 'storeFront'])->name('badge.front.store');
    Route::post('/badge/{department}/back', [BadgeDesignController::class, 'storeBack'])->name('badge.back.store');
    Route::get('/role-permissions', [RoleAccessController::class, 'index'])->name('role_permissions');
    Route::get('/role-permissions/users/search', [RoleAccessController::class, 'searchUsers'])->name('role_permissions.users.search');
    Route::get('/role-permissions/users/{user}', [RoleAccessController::class, 'showUserPermissions'])->name('role_permissions.users.show');
    Route::put('/role-permissions/users/{user}', [RoleAccessController::class, 'updateUserPermissions'])->name('role_permissions.users.update');
    Route::get('/role-permissions/roles/{role}', [RoleAccessController::class, 'showRole'])->name('role_permissions.roles.show');
    Route::put('/role-permissions/roles/{role}', [RoleAccessController::class, 'updateRolePermissions'])->name('role_permissions.roles.update');
    Route::get('/activity-log', [ActivityLogController::class, 'index'])->name('activity_log');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/profile/password', [ProfileController::class, 'updatePassword'])->name('profile.password.update');
    Route::get('/gate', [GateController::class, 'index'])->name('gate');
    Route::get('/gate/directory', [GateController::class, 'directory'])->name('gate.directory');
    Route::post('/gate/lookup', [GateController::class, 'lookup'])->name('gate.lookup');
    Route::post('/gate/submit', [GateController::class, 'submit'])->name('gate.submit');
    Route::post('/gate/sync', [GateController::class, 'sync'])->name('gate.sync');
    Route::get('/gate/plate-search', [PlateMovementController::class, 'index'])->name('gate.plate-search');
    Route::get('/gate/plate-search/results', [PlateMovementController::class, 'search'])->name('gate.plate-search.results');
});
