namespace GateVision.Api.Features.GateOperations.Domain;

public record GateConfigUpdate(
    string? CameraSource = null,
    int? ProcessingFps = null,
    string? ModelProfile = null,
    int? DetectorInputWidth = null,
    int? DetectorInputHeight = null,
    bool? ClearDetectorInputSize = null,
    double? MotionThreshold = null,
    int? MotionPixelThreshold = null,
    int? DetectMaxWidth = null,
    string? HikvisionUrl = null,
    string? HikvisionUser = null,
    string? HikvisionPassword = null,
    int? HikvisionEventTtlMs = null,
    string? HikvisionEventTypes = null,
    string? HikvisionDetectionTarget = null,
    double? MinMatchScore = null,
    double? IdentifyConfidenceThreshold = null,
    double? AutoValidateConfidence = null,
    double? MinFaceConfidence = null,
    double? TrackerMaxLostS = null,
    bool? LogUnknown = null,
    bool? TrainingMode = null,
    int? WelcomeCooldownSeconds = null,
    int? BufferTrackExpirySeconds = null,
    int? BufferPersonDedupSeconds = null,
    double? RefireScoreDelta = null,
    int? MinTrackHits = null,
    int? DeskDisplaySeconds = null,
    int? DeskEventLookbackSeconds = null,
    bool? ShowNeedsReviewOnDesk = null);
