ALTER TABLE gate_events ADD COLUMN IF NOT EXISTS "Emotion" VARCHAR(30) NULL;
ALTER TABLE gate_events ADD COLUMN IF NOT EXISTS "Age" INT NULL;
ALTER TABLE gate_events ADD COLUMN IF NOT EXISTS "Gender" VARCHAR(10) NULL;

ALTER TABLE training_events ADD COLUMN IF NOT EXISTS "Emotion" VARCHAR(30) NULL;
ALTER TABLE training_events ADD COLUMN IF NOT EXISTS "Age" INT NULL;
ALTER TABLE training_events ADD COLUMN IF NOT EXISTS "Gender" VARCHAR(10) NULL;
