-- 022: Per-gate recognition confidence thresholds (admin-configurable).
ALTER TABLE gates
ADD COLUMN IF NOT EXISTS "MinMatchScore" DOUBLE PRECISION NOT NULL DEFAULT 0.35,
  ADD COLUMN IF NOT EXISTS "IdentifyConfidenceThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0.80,
  ADD COLUMN IF NOT EXISTS "AutoValidateConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0.85,
  ADD COLUMN IF NOT EXISTS "MinFaceConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0.50;