-- 031: Per-gate welcome workflow and desk display settings.
ALTER TABLE gates
ADD COLUMN IF NOT EXISTS "WelcomeCooldownSeconds" INTEGER NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS "BufferTrackExpirySeconds" INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN IF NOT EXISTS "BufferPersonDedupSeconds" INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS "RefireScoreDelta" DOUBLE PRECISION NOT NULL DEFAULT 0.03,
  ADD COLUMN IF NOT EXISTS "MinTrackHits" INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS "DeskDisplaySeconds" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "DeskEventLookbackSeconds" INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS "ShowNeedsReviewOnDesk" BOOLEAN NOT NULL DEFAULT FALSE;